export const PASSENGER_TEMPLATE = {
  Adult: {
    type: "Adult",
    title: "Mr",
    givenName: "",
    surName: "",
    passport: "",
    passportIssue: null,
    dateOfBirth: null,
    passportExpiry: null,
    nationality: "",
  },
  Child: {
    type: "Child",
    title: "CHLD",
    givenName: "",
    surName: "",
    passport: "",
    passportIssue: null,
    dateOfBirth: null,
    passportExpiry: null,
    nationality: "",
  },
  Infant: {
    type: "Infant",
    title: "INF",
    givenName: "",
    surName: "",
    passport: "",
    passportIssue: null,
    dateOfBirth: null,
    passportExpiry: null,
    nationality: "",
  },
};
