import mongoose from "mongoose";
import bcrypt from "bcrypt";

const RegisterSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
    },
    zipId: {
      type: String,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },

    phone: {
      type: String,
      required: true,
    },

    address: {
      type: String,
      trim: true,
      default: "",
    },

    country: {
      type: String,
      trim: true,
      default: "",
    },

    city: {
      type: String,
      trim: true,
      default: "",
    },

    password: {
      type: String,
      required: true,
      minlength: 6,
      select: false, // IMPORTANT: hide password by default
    },

    // Stored for admin-generated credentials; ensure it is cleared/rotated in production
    plainPassword: {
      type: String,
    },

    isAutoGeneratedPassword: {
      type: Boolean,
      default: true,
    },

    role: {
      type: String,
      enum: ["Admin", "Agency", "SubAgent", "User"],
      default: "User",
    },

    companyName: {
      type: String,
    },

    consultant: {
      type: String,
      trim: true,
      default: "",
    },

    logo: {
      type: String,
      trim: true,
      default: "",
    },

    agencyCode: {
      type: String,
      unique: true,
      sparse: true,
    },

    status: {
      type: String,
      enum: ["Active", "Inactive", "Pending", "Suspended"],
      default: "Inactive",
    },
    priceOnCall: {
      type: Boolean,
      default: false,
    },
    showHideButton: {
      type: Boolean,
      default: true,
    },
    marginType: {
      type: String,
      enum: ["Percentage", "Amount"],
      default: "Percentage",
    },

    flightMarginPercent: {
      type: Number,
      default: 0,
    },

    flightMarginAmount: {
      type: Number,
      default: 0,
    },

    registeredFrom: {
      ipAddress: {
        type: String,
        default: "",
      },
      userAgent: {
        type: String,
        default: "",
      },
    },

    lastLogin: {
      type: Date,
    },
    activatedBy: {
      type: String,
      default: "",
    },

    activatedAt: {
      type: Date,
    },

    deactivatedBy: {
      type: String,
      default: "",
    },

    deactivatedAt: {
      type: Date,
    },
  },
  { timestamps: true },
);

/* ===========================
   PASSWORD HASHING
=========================== */
RegisterSchema.pre("save", async function () {
  if (!this.isModified("password")) return;

  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
});

/* ===========================
   PASSWORD COMPARE METHOD
=========================== */
RegisterSchema.methods.comparePassword = async function (enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

/* ===========================
   INDEXES
=========================== */
RegisterSchema.index({ email: 1 });
RegisterSchema.index({ role: 1 });

export default mongoose.model("Register", RegisterSchema);
